version: '3'
services:
  mongodb:                                  
    image: mongo:4.4.6 # name of the image
    container_name: mongodb # name of the container - this works like a hostname would
    ports: # port binding - host_port:container_port
     - 27017:27017
    environment: # environment variables
     - MONGO_INITDB_ROOT_USERNAME=admin   
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: # persistent volumes - name:directory_in_container
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongoexp
    restart: always # retry container until it succeeds - required because mongo-express will only work once mongodb is up
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
  my-app:
    image: my-app:1.0
    container_name: myapp
    restart: always
    ports:
     - 3000:3000
volumes: # definition of the volumes, in this case mongo-data is persisted locally in /var/lib/docker/volumes/my-app_mongo-data
  mongo-data:
    driver: local